In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('../artifacts/Training.csv')

In [5]:
df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [6]:
df.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4920.000000  4920.000000           4920.000000          4920.000000   
mean      0.137805     0.159756              0.021951             0.045122   
std       0.344730     0.366417              0.146539             0.207593   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4920.000000  4920.000000  4920.000000   4920.000000  4920.000000   
mean      0.021951     0.162195     0.139024      0.045122     0.045122   
std       0.146539     0.368667     0.346007      0.207593     0.207593   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  ...  pus_filled_pimples   blackheads     scurring  \
count       4920.000000  ...         4920.000000  4920.000000  4920.000000   
mean           0.021951  ...            0.021951     0.021951     0.021951   
std            0.146539  ...            0.146539     0.146539     0.146539   
min            0.000000  ...            0.000000     0.000000     0.000000   
25%            0.000000  ...            0.000000     0.000000     0.000000   
50%            0.000000  ...            0.000000     0.000000     0.000000   
75%            0.000000  ...            0.000000     0.000000     0.000000   
max            1.000000  ...            1.000000     1.000000     1.000000   

       skin_peeling  silver_like_dusting  small_dents_in_nails  \
count   4920.000000          4920.000000           4920.000000   
mean       0.023171             0.023171              0.023171   
std        0.150461             0.150461              0.150461   
min        0.000000             0.000000              0.000000   
25%        0.000000             0.000000              0.000000   
50%        0.000000             0.000000              0.000000   
75%        0.000000             0.000000              0.000000   
max        1.000000             1.000000              1.000000   

       inflammatory_nails      blister  red_sore_around_nose  \
count         4920.000000  4920.000000           4920.000000   
mean             0.023171     0.023171              0.023171   
std              0.150461     0.150461              0.150461   
min              0.000000     0.000000              0.000000   
25%              0.000000     0.000000              0.000000   
50%              0.000000     0.000000              0.000000   
75%              0.000000     0.000000              0.000000   
max              1.000000     1.000000              1.000000   

       yellow_crust_ooze  
count        4920.000000  
mean            0.023171  
std             0.150461  
min             0.000000  
25%             0.000000  
50%             0.000000  
75%             0.000000  
max             1.000000  

[8 rows x 132 columns]

In [7]:
df.shape

(4920, 133)

In [8]:
df.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)

In [9]:
df['prognosis'].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [10]:
len(df['prognosis'].unique())

41

In [11]:
X=df.drop("prognosis", axis=1)
y=df['prognosis']

In [12]:
#Encoding the labels for target column
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

In [13]:
#splitting data
X_train,X_test,y_train,y_test=train_test_split(X,y_encoded,test_size=0.2,random_state=7)
print(f"X_train:{X_train.shape}")
print(f"X_test:{X_test.shape}")
print(f"y_train:{y_train.shape}")
print(f"y_test:{y_test.shape}")

X_train:(3936, 132)
X_test:(984, 132)
y_train:(3936,)
y_test:(984,)


In [14]:
#Performance metrics calculation function
def evaluate_model(true, predicted):
    accuracy = accuracy_score(true, predicted)
    f1score = f1_score(true, predicted, average='macro')
    return accuracy, f1score

In [15]:
#Training different models
models = {
    "Logictic Regression" : LogisticRegression(),
    "Logistic Regression with L1 Regularization": LogisticRegression(penalty='l1', solver='liblinear'),
    "Logistic Regression with L2 Regularization": LogisticRegression(penalty='l2'),
    "K-Neighbors Classifier": KNeighborsClassifier(),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "Random Forest Classifier": RandomForestClassifier(),
    "XGBClassifier": XGBClassifier(), 
    'MultinomialNB': MultinomialNB(),
    'SVC': SVC(kernel='linear')
}

model_list= []
accuracy_list= []
f1score_list=[]

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)

    y_train_pred= model.predict(X_train)
    y_test_pred= model.predict(X_test)

    model_train_accuracy, model_train_f1score = evaluate_model(y_train, y_train_pred)
    model_test_accuracy, model_test_f1score = evaluate_model(y_test, y_test_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    
    print('\nModel performance for Training set')
    print("- Accuracy: {:.4f}".format(model_train_accuracy))
    print("- F1 Score: {:.4f}".format(model_train_f1score))

    print('-'*35)
    
    print('Model performance for Test set')
    print("- Accuracy: {:.4f}".format(model_test_accuracy))
    print("- F1 Score: {:.4f}".format(model_test_f1score))
    print("- Confusion Matrix:")
    print(confusion_matrix(y_test, y_test_pred))
    print("- Classification Report:")
    print(classification_report(y_test, y_test_pred))

    accuracy_list.append(model_test_accuracy)
    f1score_list.append(model_test_f1score)
    
    print('='*35)
    print('\n')
    

Logictic Regression

Model performance for Training set
- Accuracy: 1.0000
- F1 Score: 1.0000
-----------------------------------
Model performance for Test set
- Accuracy: 1.0000
- F1 Score: 1.0000
- Confusion Matrix:
[[21  0  0 ...  0  0  0]
 [ 0 23  0 ...  0  0  0]
 [ 0  0 31 ...  0  0  0]
 ...
 [ 0  0  0 ... 19  0  0]
 [ 0  0  0 ...  0 28  0]
 [ 0  0  0 ...  0  0 24]]
- Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      1.00      1.00        23
           2       1.00      1.00      1.00        31
           3       1.00      1.00      1.00        27
           4       1.00      1.00      1.00        23
           5       1.00      1.00      1.00        28
           6       1.00      1.00      1.00        25
           7       1.00      1.00      1.00        25
           8       1.00      1.00      1.00        25
           9       1.00      1.00      1.00        28
     

In [16]:
results = pd.DataFrame(list(zip(model_list, accuracy_list, f1score_list)), columns=['Model Name', 'Accuracy', 'F1 Score'])

In [17]:
results.sort_values(by=["Accuracy", "F1 Score"], ascending=False)

Model Name  Accuracy  F1 Score
0                         Logictic Regression       1.0       1.0
1  Logistic Regression with L1 Regularization       1.0       1.0
2  Logistic Regression with L2 Regularization       1.0       1.0
3                      K-Neighbors Classifier       1.0       1.0
4                    Decision Tree Classifier       1.0       1.0
5                    Random Forest Classifier       1.0       1.0
6                               XGBClassifier       1.0       1.0
7                               MultinomialNB       1.0       1.0
8                                         SVC       1.0       1.0

In [18]:
#Selectiong Logistic Regression
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_pred = log_reg.predict(X_test)
accuracy_score(y_test,y_pred)

1.0

In [19]:
#Saving the model
import pickle
pickle.dump(log_reg, open('log_reg.pkl','wb'))

In [20]:
#Load the model
logReg= pickle.load(open('log_reg.pkl', 'rb'))

In [21]:
#Quick Test
pred = logReg.predict(X_test.iloc[1].values.reshape(1,-1))
print("Predicted Disease :", logReg.predict(X_test.iloc[1].values.reshape(1,-1)))
print("Actual Disease :", y_test[0])

Predicted Disease : [16]
Actual Disease : 18


In [22]:
label_encoder.inverse_transform(pred)[0]

'GERD'

In [23]:
import os
file = os.path.join('../artifacts', 'model.pkl')
m= pickle.load(open(file, 'rb'))

In [48]:
pred = m.predict(X_test.iloc[821].values.reshape(1,-1))
print("Predicted Disease :", pred)
print("Actual Disease :", y_test[821])
print(label_encoder.inverse_transform(pred)[0])
print(label_encoder.inverse_transform(y_test[821].reshape(1,1))[0])


Predicted Disease : [7]
Actual Disease : 7
Cervical spondylosis
Cervical spondylosis
